#!/bin/sh

# mount /pref
touch /tmp/FL0/.exist 2>/dev/null
if [ -e /tmp/FL0/.exist ]; then
	mkdir -p /tmp/FL0/pref
	mount --bind /tmp/FL0/pref /pref
    cp /usr/local/share/script/wifi.conf /tmp/
    if [ -e /tmp/FL0/pref/bt_ble_client_devices.xml ]; then
        cp /tmp/FL0/pref/bt_ble_client_devices.xml /tmp/
    fi
    if [ -e /tmp/FL0/pref/bt_hh_devices.xml ]; then
        cp /tmp/FL0/pref/bt_hh_devices.xml /tmp/
    fi
    if [ -e /tmp/FL0/pref/bt_devices.xml ]; then
        cp /tmp/FL0/pref/bt_devices.xml /tmp/
    fi
    if [ -e /tmp/FL0/pref/bt_config.xml ]; then
        cp /tmp/FL0/pref/bt_config.xml /tmp/
    fi
else
	echo 'Warning: a:\ is offline!'
	mkdir /tmp/pref
	mount --bind /tmp/pref /pref
fi
cp /usr/local/share/script/ble_rc_devices.xml /tmp/

exit $?
