#!/bin/sh

echo 'S99bootdone is running...'

#detect Wi-Fi chip, send boot_done to RTOS
/usr/local/share/script/chip.detecting.sh &

#send boot_done to RTOS
if [ -x /usr/bin/SendToRTOS ]; then
    /usr/bin/SendToRTOS boot_done
fi

exit $?
